# fly.toml
app = "bot-crm-worker"   # назва твого застосунку

[processes]
app    = "uvicorn app_web.main:app --host 0.0.0.0 --port 8080"
worker = "python -m worker.report_worker"

# HTTP-обслуговування — лише для web-групи
[http_service]
internal_port = 8080
force_https = true
auto_start_machines = true
auto_stop_machines  = "off"
min_machines_running = 1

# (Опційно) healthcheck, щоб розгортання чекало готовність вебу
[[checks]]
  grace_period = "5s"
  interval = "10s"
  timeout = "2s"
  type = "http"
  [checks.http]
    method = "GET"
    path = "/"
    protocol = "http"
    port = 8080
