app = "your-telegram-bitrix-bot"
primary_region = "waw"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  processes = ["app"]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"

# Якщо матимете другу машину для воркера:
[processes]
  app = "uvicorn app_web.main:app --host 0.0.0.0 --port 8080"
  worker = "python -m worker.report_worker"
